# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmUse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Realm', '~> 3.0.2'
  # Pods for RealmUse

end

target 'RealmUseTests' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    pod 'Realm', '~> 3.0.2'
    # Pods for RealmUse
    
end



